{
  "special_tokens": {
    "think_start": 151667,
    "think_end": 151668
  },
  "quick": {
    "model_name": "Qwen3-4B",
    "model_path": "Qwen/Qwen3-4B",
    "param": "4",
    "mem_fraction_static": 0.30
  },
  "reference": {
    "model_name": "Qwen3-8B",
    "model_path": "Qwen/Qwen3-8B",
    "param": "8",
    "mem_fraction_static": 0.65
  },
  "continuation_main": {
    "model_name": "Qwen3-8B",
    "model_path": "Qwen/Qwen3-8B",
    "param": "8",
    "tp_size": 2,
    "base_gpu_id": 2,
    "mem_fraction_static": 0.90
  },
  "continuation_reference": {
    "model_name": "Qwen3-8B",
    "model_path": "Qwen/Qwen3-8B",
    "param": "8",
    "tp_size": 1,
    "base_gpu_id": 3,
    "mem_fraction_static": 0.90
  },
  "verify": {
    "model_name": "Qwen2.5-72B-Instruct",
    "model_path": "Qwen/Qwen2.5-72B-Instruct",
    "mem_fraction_static": 0.90,
    "max_new_tokens": 16,
    "base_gpu_id": 4,
    "tp_size": 4
  },
  "router": {
    "router_name": "Qwen3-4B+Qwen3-8B",
    "router_path": "GY2233/Qwen3_4B_Qwen_8B", 
    "override_init_args":{
      "pretrained_model_name": "Qwen/Qwen3-4B"
    }
  }
}